import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import { FC, PropsWithChildren } from 'react'
import './globals.css'

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
	title: 'Chat AI',
	description: 'Generated by create next app'
}

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
	return (
		<html lang='en'>
			<body className={fontSans.className}>{children}</body>
		</html>
	)
}

export default RootLayout
